version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: university-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    container_name: university-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: university-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    container_name: university-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"   # HTTP browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  mysql_data:
  mongo_data:
  redis_data:
  neo4j_data:
