services:
  postgres:
    image: postgres:14
    container_name: cs440_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: cs440_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  neo4j:
    image: neo4j:5
    container_name: cs440_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  mongodata:
  neo4jdata:

networks:
  default:
    driver: bridge
